apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: computer
rules:
- apiGroups: ["sms.dev"]
  resources: ["clusters", "computers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["sms.dev"]
  resources: ["computers"]
  verbs: ["create", "delete"]
- apiGroups: ["sms.dev"]
  resources: ["computers/status"]
  verbs: ["update", "patch"]
