name: PR Checks
on: [ pull_request ]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      run: |
        sudo add-apt-repository ppa:jackmacwindows/ppa && \
        apt-get -y -qq update && \
        apt-get -y -qq install craftos-pc
    
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    
    - name: Run tests
      run: ./craftos --headless --script src/chatbot.lua || echo $? > ~/.retval
      continue-on-error: true
      timeout-minutes: 2
    
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
